export enum ErrorMessage {
  NO_IMAGE_DATA = "No image data",
  INVALID_TOKEN_DATA = "Wrong token data",
  INVALID_TOKEN_TYPE = "Invalid token type",
  INVALID_FETCH_DATA = "Invalid fetch data",
  INVALID_VERIFICATION_CODE = "Verification code does not correct",
  CONTAMINATED_TOKEN = "Get contaminated token",
  MODIFY_OTHER_USER = "Attempting to modify other people's information",
  USER_NOT_VERIFIED = "Invalid user data",
  USER_NOT_EXISTS = "User not exists in database",
  USER_VERIFICATION_REQUIRED = "User verification required",
  EXPIRED_VERIFICATION_CODE = "Verification code has been expired",
  DUPLICATED_NICKNAME = "User nickname duplicated",
  DUPLICATED_EMAIL = "User already exists in database",
  POST_NOT_EXISTS = "Post not exists in database",
  TOO_MANY_REQUEST = "Try to send too many requests",
  INTERNAL_SERVER_ERROR = "Internal server error",
  DB_CONNECTION_ERROR = "Connection error to database",
  GATEWAY_ERROR = "Bad gateway",
}
