export enum ErrorMessage {
  NO_IMAGE_DATA = "No image data",
  INVALID_TOKEN_DATA = "Wrong token data",
  INVALID_TOKEN_TYPE = "Invalid token type",
  TOKEN_CONTAMINATED = "Get contaminated token",
  MODIFY_OTHER_USER = "Attempting to modify other people's information",
  USER_NOT_VERIFIED = "Invalid user data",
  USER_NOT_EXISTS = "User not exists in database",
  USER_VERIFICATION_REQUIRED = "User verification required",
  VERIFICATION_CODE_EXPIRED = "Verification code has been expired",
  INVALID_VERIFICATION_CODE = "Verification code does not correct",
  NICKNAME_DUPLICATED = "User nickname duplicated",
  POST_NOT_EXISTS = "Post not exists in database",
  TOO_MANY_REQUEST = "Try too many requests",
  INTERNAL_SERVER_ERROR = "Internal server error",
  DB_CONNECTION_ERROR = "Connection error to database",
  GATEWAY_ERROR = "Bad gateway",
}
